### PR TITLE
added createrepo  to the startup

### PR DESCRIPTION
**Pull request by snoby**
Added createrepo update to the startup file.  When mounting an existing
named docker data volume the xml data would not update.

### CODE REVIEW

**Comment by snoby** [comment]
If I have a docker named volume that has been populated by another docker container, then startup the yum repo docker container the creation of the repo would not happen.  I worked around this by adding the createrepo --update command in the startup script.

**Comment by dgutierrez1287** [comment]
The thing I see is this would work if there was only a single repo but if you have a structure of many repos this would not fit that case. there could be a second modified version of the scan script that runs at startup and does an initial scan and that would allow for the same spirit of not pushing a single type of repo structure.

**Comment by snoby** [comment]
I agree with your opinion.  I was just implementing a quick and dirty fix.

**Comment by dgutierrez1287** [comment]
I have actually done a full re-write changing over to go which will no do a repo scan at startup as well as many other things.

**Pull request closed without merging**
